//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public long AppealID { get; set; }
        public long EventID { get; set; }
        public string AppealContent { get; set; }
        public int AppealStatus { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<long> HandleBy { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
