//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.Events = new HashSet<Event>();
        }
    
        public long ChannelID { get; set; }
        public long UserID { get; set; }
        public string ChannelName { get; set; }
        public string ChannelDescription { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
