//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentID { get; set; }
        public long EventID { get; set; }
        public long UserID { get; set; }
        public string CommentContent { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
