//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventImage
    {
        public long EventImageID { get; set; }
        public Nullable<long> EventID { get; set; }
        public Nullable<long> ImageID { get; set; }
        public Nullable<bool> Approve { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Image Image { get; set; }
    }
}
