//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventZoneEntities : DbContext
    {
        public EventZoneEntities()
            : base("name=EventZoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Appeal> Appeals { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryFollow> CategoryFollows { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventFollow> EventFollows { get; set; }
        public virtual DbSet<EventImage> EventImages { get; set; }
        public virtual DbSet<EventPlace> EventPlaces { get; set; }
        public virtual DbSet<EventRank> EventRanks { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<LikeDislike> LikeDislikes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationChange> NotificationChanges { get; set; }
        public virtual DbSet<NotificationObject> NotificationObjects { get; set; }
        public virtual DbSet<PeopleFollow> PeopleFollows { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportDefine> ReportDefines { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<TrackingAction> TrackingActions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
