//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPlace
    {
        public EventPlace()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public long EventPlaceID { get; set; }
        public long EventID { get; set; }
        public long LocationID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
