//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.EventImages = new HashSet<EventImage>();
            this.Users = new HashSet<User>();
        }
    
        public long ImageID { get; set; }
        public long UserID { get; set; }
        public string ImageLink { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual ICollection<EventImage> EventImages { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
