//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationObjects = new HashSet<NotificationObject>();
        }
    
        public long ID { get; set; }
        public long UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<NotificationObject> NotificationObjects { get; set; }
    }
}
