//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDefine
    {
        public ReportDefine()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int ReportTypeID { get; set; }
        public string ReportTypeName { get; set; }
        public string ReportDefine1 { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
