//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public long VideoID { get; set; }
        public long EventPlaceID { get; set; }
        public string VideoLink { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Privacy { get; set; }
        public string PrimaryServer { get; set; }
        public string BackupServer { get; set; }
        public string StreamName { get; set; }
    
        public virtual EventPlace EventPlace { get; set; }
    }
}
